filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: http://bucketrepo-jx.192.168.49.2.nip.io/bucketrepo/charts/
releases:
- chart: dev/jx-aspnet-app002
  version: 0.0.17
  name: jx-aspnet-app002
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
