apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: hughexp
    provider: github
    repository: python01
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: hughexp-python01
  namespace: jx
spec:
  httpCloneURL: https://github.com/hughexp/python01.git
  org: hughexp
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: python01
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/hughexp/python01
