filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-production
repositories:
- name: dev
  url: http://bucketrepo-jx.192.168.49.2.nip.io/bucketrepo/charts/
releases:
- chart: dev/python01
  version: 0.0.1
  name: python01
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
